### ISSUE TITLE
Curriculum order? 

### ISSUE THREAD

**Issue by LNKeat** [learn-co-curriculum/phase-3-enumerables-debugging#1]
### Canvas Link

https://learning.flatironschool.com/courses/4323/pages/enumerables-debugging-with-pry?module_item_id=277346

### Concern

This lesson talks about how Pry works and how to deal with different issues related to it including the screenshot and a few other helpful references.  
I was really struggling with all these issues in the Ruby Fundamentals section and this info would have been REALLY helpful back then.    
Is there a reason it's not talked about in either the Debugging: Pry or Control Flow: Loops lessons?   

### Additional Context

![Screen Shot 2021-11-10 at 9 14 49 PM](https://user-images.githubusercontent.com/81266679/141236274-b3dbcd42-e7f2-4d1c-b66c-2b68fe5a4ada.png)

### Suggested Changes

see above

**Comment by ihollander** [comment]
Hi @LNKeat - thanks for the suggestion! I agree, this information is useful and a common cause of frustration when getting started with Pry. We'll update the [Debugging with Pry](https://github.com/learn-co-curriculum/phase-3-debugging-with-pry) lesson to include this information as well.

**Comment by ihollander** [comment]
Closed by https://github.com/learn-co-curriculum/phase-3-debugging-with-pry/pull/2
